<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Pieza.aspx.cs" Inherits="Ejemplo.Web.Pieza" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
    <style type="text/css">
        .auto-style1 {
            height: 215px;
            width: 497px;
        }
        .auto-style2 {
            height: 215px;
            width: 314px;
        }
        .auto-style3 {
            width: 788px;
        }
        .auto-style4 {
            height: 26px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <h2>
        Administración de PIEZAS</h2>
    <br />
    <center>
        <table class="auto-style3">
            <tr>
                <td class="auto-style1">
                    <table>
                        <tr>
                            <td align="left">
                                <asp:Label ID="lblId_P" Text="Id:" runat="server" ></asp:Label>
                            </td>
                            <td>
                                <asp:TextBox ID="txtId" runat="server" ></asp:TextBox>
                            </td>
                            <td>
                                 <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="El Id es obligatorio" ControlToValidate="txtId"></asp:RequiredFieldValidator>
                            </td>
                        </tr>
                         <tr>
                            <td align="left">
                                <asp:Label ID="lblNombre" Text="Nombre:" runat="server" ></asp:Label>
                            </td>
                            <td>
                                <asp:TextBox ID="txtNombreP" runat="server" ></asp:TextBox>
                            </td>
                            <td>
                                 <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ErrorMessage="El Nombre es obligatorio" ControlToValidate="txtNombreP"></asp:RequiredFieldValidator>
                            </td>
                        </tr>
                          <tr>
                            <td align="left">
                                <asp:Label ID="Label1" Text="Valor:" runat="server" ></asp:Label>
                            </td>
                            <td>
                                <asp:TextBox ID="txtValorP" runat="server"></asp:TextBox>
                            </td>
                            <td>
                                 <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ErrorMessage="El Valor es obligatorio" ControlToValidate="txtValorP"></asp:RequiredFieldValidator>
                            </td>
                        </tr>   
                         <tr>
                            <td align="left">
                                <asp:Label ID="Label2" Text="Sector y Actividad:" runat="server"></asp:Label>
                            </td>
                            <td>
                                <asp:DropDownList ID="DDLSectorPieza" AutoPostBack="true" runat="server" ></asp:DropDownList>
                            </td>
                            <td>
                                 <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ErrorMessage="El Sector y Actividad es obligatorio" ControlToValidate="DDLSectorPieza"></asp:RequiredFieldValidator>
                            </td>
                        </tr>
                           
                        <tr>   
                            <td colspan ="3" align="left">
                                <asp:Label ID="lblResultado" runat="server"></asp:Label>
                            </td>
                        </tr>
                         <tr>
                            <td colspan="2" align="center">
                                <asp:Button ID="btnAgregar" Text="Agregar" runat="server" OnClick="btnAgregar_Click" />
                                <asp:Button ID="btnActualizar" runat="server" Text="Modificar" Visible="false" OnClick="btnActualizar_Click" />
                                <asp:Button ID="btnCancelar" runat="server" Text="Cancelar" Visible="false" OnClick="btnCancelar_Click" />
                            </td>
                        </tr>
                    </table>
                </td>
                <td class="auto-style2">
                    <table>
                        <tr>
                            <td>
                                <asp:GridView ID="grdPieza" Width="100%" runat="server"
                                    ViewStateMode="Enabled" CellPadding="4" ForeColor="#333333" GridLines="None"
                                    AutoGenerateDeleteButton="True" OnRowDeleting="grdPieza_RowDeleting" AutoGenerateSelectButton="True"
                                    OnSelectedIndexChanging="grdPieza_SelectedIndexChanging" EmptyDataText="No hay datos ingresados"
                                    ShowHeaderWhenEmpty="True" >
                                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                                    <EditRowStyle BackColor="#999999" />
                                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                                    <SortedAscendingCellStyle BackColor="#E9E7E2" />
                                    <SortedAscendingHeaderStyle BackColor="#506C8C" />
                                    <SortedDescendingCellStyle BackColor="#FFFDF8" />
                                    <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                                </asp:GridView>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </center>
</asp:Content>
