<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Trabaja.aspx.cs" Inherits="Ejemplo.Web.Trabaja" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
        <style type="text/css">
        .auto-style1 {
            height: 215px;
            width: 497px;
        }
        .auto-style3 {
            width: 788px;
        }
            .auto-style7 {
                width: 65px;
            }
            .auto-style8 {
                width: 60px;
            }
            .auto-style9 {
                width: 46px;
            }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <h2>
        Asignar automovil y sector a operario</h2>
    <br />
    <center>
    <table class="auto-style3">
        <tr>
            <td class="auto-style1">
                <table style="width: 100%">
                        <tr>
                            <td align="left">
                                <asp:Label ID="lblModelo" Text="Modelo:" runat="server" ></asp:Label>
                            </td>
                            <td align="left">
                                <asp:DropDownList ID="DDLModelo" AutoPostBack="true" runat="server" Visible="true" OnSelectedIndexChanged="DDLModelo_SelectedIndexChanged"  ></asp:DropDownList>
                            </td>
                            <td align="left" class="auto-style8">
                                <asp:Label ID="lblOperario" Text="Operario:" runat="server" ></asp:Label>
                            </td>
                            <td align="left">
                                <asp:DropDownList ID="DDLOperario" runat="server" Visible="true"></asp:DropDownList>
                            </td>
                            <td align="left" class="auto-style9">
                                <asp:Label ID="lblSector" Text="Sector:" runat="server" ></asp:Label>
                            </td>
                            <td align="left">
                                <asp:DropDownList ID="DDLSector" runat="server" Visible="true"></asp:DropDownList>
                            </td>
                            
                        </tr>
                        <tr>
                            <td align="right">
                                <asp:Label ID="lblCantHoras" Text="Cantidad de horas:" runat="server" ></asp:Label>
                            </td>
                            <td  align="center">
                                <asp:TextBox ID="txtCantHoras" runat="server" Enabled="true"></asp:TextBox>
                            </td>
                            <td class="auto-style9">
                                <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="la cantidad de horas es obligatorio" ControlToValidate="txtCantHoras"></asp:RequiredFieldValidator>
                            </td>
                        </tr>                 
                        <tr>   
                            <td align="left">
                                <asp:Label ID="lblResultado" runat="server"></asp:Label>
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                <asp:Button ID="btnAgregar" Text="Agregar" runat="server" OnClick="btnAgregar_Click" />
                            </td>
                        </tr>
                    <tr>
                        <td >
                            <table>
                                <tr>
                                    <td>
                            <asp:GridView ID="grdTrabaja" Width="100%" runat="server"
                                    ViewStateMode="Enabled" CellPadding="4" ForeColor="#333333" GridLines="None" AutoGenerateColumns="true"
                                    EmptyDataText="No hay datos ingresados"
                                    ShowHeaderWhenEmpty="True" AutoGenerateDeleteButton="True" OnRowDeleting="grdTrabaja_RowDeleting" >
                                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                                    <EditRowStyle BackColor="#999999" />
                                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                                    <SortedAscendingCellStyle BackColor="#E9E7E2" />
                                    <SortedAscendingHeaderStyle BackColor="#506C8C" />
                                    <SortedDescendingCellStyle BackColor="#FFFDF8" />
                                    <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                                </asp:GridView>
                                        </td>
                                    </tr>
                                </table>
                        </td>
                    </tr>
                    </table>
            </td>
        </tr>
    </table>
</asp:Content>
